### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Qavai** [hobbyquaker/ccu.io#160]
Скажите, система сейчас проектируется и дальше и будет развиваться?

Стоит ли её применять или есть что-то новое (другое)?

**Comment by j-cooper** [comment]
Сорри, ушёл на openhub. 10.01.2018, 10:53, "Eugene Ivanov" <notifications@github.com>:Скажите, система сейчас проектируется и дальше и будет развиваться?Стоит ли её применять или есть что-то новое (другое)?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
